# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Song.create({:artist_id => 1, :title => "Free Fallin'"})
Song.create({:artist_id => 1, :title => "I Won't Back Down"})
Song.create({:artist_id => 1, :title => "You Wreck Me"})
Song.create({:artist_id => 1, :title => "The Waiting"})
Song.create({:artist_id => 1, :title => "Refugee"})
Song.create({:artist_id => 2, :title => "Vava Voom"})
Song.create({:artist_id => 2, :title => "The 808 Track"})
Song.create({:artist_id => 2, :title => "Bass Head"})
Song.create({:artist_id => 3, :title => "Blame"})
Song.create({:artist_id => 3, :title => "Outside"})
Song.create({:artist_id => 4, :title => "Five More Hours"})
Song.create({:artist_id => 5, :title => "This Is How We Roll"})
Song.create({:artist_id => 6, :title => "Never Say Goodbye"})
Song.create({:artist_id => 6, :title => "Apollo"})
Song.create({:artist_id => 7, :title => "No Faith In Brooklyn"})
Song.create({:artist_id => 8, :title => "Stolen Dance"})
Song.create({:artist_id => 9, :title => "Air Force Ones"})
Song.create({:artist_id => 10, :title => "Prayer In C"})
Song.create({:artist_id => 10, :title => "Headlights"})
Song.create({:artist_id => 10, :title => "Sun Goes Down"})
Song.create({:artist_id => 11, :title => "Red Lights"})
Song.create({:artist_id => 11, :title => "Set Yourself Free"})
Song.create({:artist_id => 11, :title => "Shimmer"})
Song.create({:artist_id => 11, :title => "Close To Me"})
Song.create({:artist_id => 11, :title => "Footprints"})
Song.create({:artist_id => 11, :title => "Last Train"})
Song.create({:artist_id => 12, :title => "Beautiful Day"})
Song.create({:artist_id => 12, :title => "With Or Without You"})
Song.create({:artist_id => 12, :title => "Pride"})
Song.create({:artist_id => 12, :title => "One"})
Song.create({:artist_id => 12, :title => "The Miracle"})

Artist.create({:artist => "Tom Petty"})
Artist.create({:artist => "Bassnectar"})
Artist.create({:artist => "Calvin Harris"})
Artist.create({:artist => "Chris Brown"})
Artist.create({:artist => "Florida Georgia Line"})
Artist.create({:artist => "Hardwell"})
Artist.create({:artist => "Hoodie Allen"})
Artist.create({:artist => "Milky Chance"})
Artist.create({:artist => "Nelly"})
Artist.create({:artist => "Robin Schulz"})
Artist.create({:artist => "Tiesto"})
Artist.create({:artist => "U2"})

Playlist.create({:playlist => "Workout"})
Playlist.create({:playlist => "Relax"})
Playlist.create({:playlist => "Favorites"})

Playlisting.create({:playlist_id => 1, :song_id => 6})
Playlisting.create({:playlist_id => 1, :song_id => 7})
Playlisting.create({:playlist_id => 1, :song_id => 8})
Playlisting.create({:playlist_id => 1, :song_id => 11})
Playlisting.create({:playlist_id => 1, :song_id => 13})
Playlisting.create({:playlist_id => 1, :song_id => 14})
Playlisting.create({:playlist_id => 1, :song_id => 17})
Playlisting.create({:playlist_id => 1, :song_id => 21})
Playlisting.create({:playlist_id => 1, :song_id => 22})

Playlisting.create({:playlist_id => 2, :song_id => 1})
Playlisting.create({:playlist_id => 2, :song_id => 2})
Playlisting.create({:playlist_id => 2, :song_id => 8})
Playlisting.create({:playlist_id => 2, :song_id => 26})
Playlisting.create({:playlist_id => 2, :song_id => 27})
Playlisting.create({:playlist_id => 2, :song_id => 28})

Playlisting.create({:playlist_id => 3, :song_id => 1})
Playlisting.create({:playlist_id => 3, :song_id => 2})
Playlisting.create({:playlist_id => 3, :song_id => 3})
Playlisting.create({:playlist_id => 3, :song_id => 7})
Playlisting.create({:playlist_id => 3, :song_id => 10})
Playlisting.create({:playlist_id => 3, :song_id => 11})
Playlisting.create({:playlist_id => 3, :song_id => 14})
Playlisting.create({:playlist_id => 3, :song_id => 15})
Playlisting.create({:playlist_id => 3, :song_id => 16})
Playlisting.create({:playlist_id => 3, :song_id => 17})
Playlisting.create({:playlist_id => 3, :song_id => 22})
Playlisting.create({:playlist_id => 3, :song_id => 25})
Playlisting.create({:playlist_id => 3, :song_id => 26})
Playlisting.create({:playlist_id => 3, :song_id => 27})
Playlisting.create({:playlist_id => 3, :song_id => 30})